export const english = {
  title: 'experience another level',
  paragraph: 'Our travel experts and lifestyle managers have a selection of the finest villas, yachts, restaurants, clubs, spas, tailor-made activities, luxury products, bespoke events, and experiences. We strive to offer an unparalleled level of service tailored to each of our guests.',
  subTitle: "Luxury holidays are not about price. It's about quality.",
  servicesTitle1: 'concierge',
  servicesParagraph1: 'VIP Bookings & Reservations 24/7 Errand Support',
  servicesTitle2: 'food & bar services',
  servicesParagraph2: 'Private chef | Bartender | Butler | Waiter',
  servicesTitle3: 'vip transfer',
  servicesParagraph3: 'Private driver | Luxury cars | Jets | Helicopters',
  servicesTitle4: 'vip security',
  servicesParagraph4: 'Static & Close Protection | K9 Dogs  Money Shipments | Security Systems',
  servicesTitle5: 'aesthetic services',
  servicesParagraph5: 'Hair Stylist | Nails Specialist | Massage Personal Trainer | Yoga Teacher',
};

export const portuguese = {
  title: 'experimente outro nível',
  paragraph: 'Nossos especialistas em viagens e gerentes de estilo de vida têm uma seleção das melhores vilas, iates, restaurantes, clubes, spas, atividades sob medida, produtos de luxo, eventos e experiências personalizadas. Nós nos esforçamos para oferecer um nível incomparável de serviço customizado para cada um de nossos hóspedes.',
  subTitle: 'Férias de luxo não têm a ver com preço. É sobre qualidade.',
  servicesTitle1: 'concierge vip',
  servicesParagraph1: 'Reservas VIP | Suporte 24 Horas | Assistência Personalizada',
  servicesTitle2: 'food & bar services',
  servicesParagraph2: 'Private chef | Bartender | Butler | Waiter',
  servicesTitle3: 'transfer vip',
  servicesParagraph3: 'Motorista Particular | Carros de Luxo | Jatos Particulares | Helicópteros',
  servicesTitle4: 'segurança vip',
  servicesParagraph4: 'Proteção Estática e Próxima | Cães Policiais Remessas de Dinheiro | Sistemas de segurança',
  servicesTitle5: 'serviços estéticos',
  servicesParagraph5: 'Cabeleireiro | Manicure | Massagista Personal Trainer | Professor de Ioga',
};

export const spanish = {
  title: 'experience another level',
  paragraph: 'Our travel experts and lifestyle managers have a selection of the finest villas, yachts, restaurants, clubs, spas, tailor-made activities, luxury products, bespoke events, and experiences. We strive to offer an unparalleled level of service tailored to each of our guests.',
  subTitle: "Luxury holidays are not about price. It's about quality.",
  servicesTitle1: 'concierge',
  servicesParagraph1: 'VIP Bookings & Reservations 24/7 Errand Support',
  servicesTitle2: 'food & bar services',
  servicesParagraph2: 'Private chef | Bartender | Butler | Waiter',
  servicesTitle3: 'vip transfer',
  servicesParagraph3: 'Private driver | Luxury cars | Jets | Helicopters',
  servicesTitle4: 'vip security',
  servicesParagraph4: 'Static & Close Protection | K9 Dogs  Money Shipments | Security Systems',
  servicesTitle5: 'aesthetic services',
  servicesParagraph5: 'Hair Stylist | Nails Specialist | Massage Personal Trainer | Yoga Teacher',
};
