CREATE SCHEMA IF NOT EXISTS `MyconianLuxury` ;

USE `MyconianLuxury` ;

CREATE TABLE IF NOT EXISTS `MyconianLuxury`.`blog` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `tags` VARCHAR(100),
  `cover` VARCHAR(45),
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `text1` VARCHAR(1000) NOT NULL,
  `image1` VARCHAR(45),
  `text2` VARCHAR(1000),
  `image2` VARCHAR(45),
  `text3` VARCHAR(1000),
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `MyconianLuxury`.`villas` (
  `villas_id` INT NOT NULL AUTO_INCREMENT,
  `villas_name` VARCHAR(100) NOT NULL,
  `cover` VARCHAR(200) NOT NULL DEFAULT '',
  `rooms` INT NOT NULL,
  `baths` INT NOT NULL,
  `guests` INT NOT NULL,
  PRIMARY KEY (`villas_id`),
  UNIQUE KEY `villas_name` (villas_name)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `MyconianLuxury`.`villas_imgs` (
  `villas_imgs_id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(200) NOT NULL DEFAULT '',
  `villas_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`villas_imgs_id`)
) ENGINE = InnoDB;

INSERT INTO MyconianLuxury.villas (villas_name, cover, rooms, baths, guests) 
VALUES 
('Aphrodite', 'http://localhost:3001/villas/cover/Aphrodite.jpeg', 1, 1, 1),
('Artemis', 'http://localhost:3001/villas/cover/Artemis.jpg', 1, 1, 1),
('Astrea', 'http://localhost:3001/villas/cover/Astrea.jpg', 1, 1, 1),
('Athena', 'http://localhost:3001/villas/cover/Athena.jpg', 1, 1, 1),
('Bia', 'http://localhost:3001/villas/cover/Bia.jpg', 1, 1, 1),
('Brizo', 'http://localhost:3001/villas/cover/Brizo.jpg', 1, 1, 1),
('Calypso', 'http://localhost:3001/villas/cover/Calypso.jpg', 1, 1, 1),
('Cybele', 'http://localhost:3001/villas/cover/Cybele.jpg', 1, 1, 1),
('Demeter', 'http://localhost:3001/villas/cover/Demeter.jpg', 1, 1, 1),
('Dione', 'http://localhost:3001/villas/cover/Dione.jpg', 1, 1, 1),
('Electra', 'http://localhost:3001/villas/cover/Electra.jpg', 1, 1, 1),
('Eos', 'http://localhost:3001/villas/cover/Eos.jpg', 1, 1, 1),
('Erato', 'http://localhost:3001/villas/cover/Erato.jpg', 1, 1, 1),
('Gaia', 'http://localhost:3001/villas/cover/Gaia.jpg', 1, 1, 1),
('Harmonia', 'http://localhost:3001/villas/cover/Harmonia.jpg', 1, 1, 1),
('Hera', 'http://localhost:3001/villas/cover/Hera.jpg', 1, 1, 1),
('Irene', 'http://localhost:3001/villas/cover/Irene.jpg', 1, 1, 1),
('Iris', 'http://localhost:3001/villas/cover/Iris.jpg', 1, 1, 1),
('Keres', 'http://localhost:3001/villas/cover/Keres.jpg', 1, 1, 1),
('Maia', 'http://localhost:3001/villas/cover/Maia.jpg', 1, 1, 1),
('Nix', 'http://localhost:3001/villas/cover/Nix.jpg', 1, 1, 1),
('Persephone', 'http://localhost:3001/villas/cover/Persephone.jpg', 1, 1, 1),
('Phoebe', 'http://localhost:3001/villas/cover/Phoebe.jpg', 1, 1, 1),
('Selene', 'http://localhost:3001/villas/cover/Selene.jpg', 1, 1, 1),
('Thalassa', 'http://localhost:3001/villas/cover/Thalassa.jpg', 1, 1, 1);

INSERT INTO MyconianLuxury.villas_imgs (url, villas_name) 
VALUES 
('http://localhost:3001/villas/Aphrodite/Aphrodite1.jpg', 'Aphrodite'),
('http://localhost:3001/villas/Astrea/Astrea1.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea2.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea3.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea4.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea5.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea6.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea7.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea8.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea9.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea10.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea11.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea12.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea13.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea14.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea15.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea16.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea17.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea18.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea19.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea20.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea21.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea22.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea23.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea24.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea25.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea26.jpg', 'Astrea'),
('http://localhost:3001/villas/Astrea/Astrea27.jpg', 'Astrea'),
('http://localhost:3001/villas/Cybele/Cybele1.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele2.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele3.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele4.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele5.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele6.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele7.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele8.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele9.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele10.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele11.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele12.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele13.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele14.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele15.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele16.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele17.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele18.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele19.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele20.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele21.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele22.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele23.jpg', 'Cybele'),
('http://localhost:3001/villas/Cybele/Cybele24.jpg', 'Cybele'),
('http://localhost:3001/villas/Persephone/Persephone1.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone2.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone3.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone4.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone5.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone6.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone7.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone8.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone9.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone10.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone11.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone12.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone13.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone14.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone15.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone16.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone17.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone18.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone19.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone20.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone21.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone22.jpg', 'Persephone'),
('http://localhost:3001/villas/Persephone/Persephone22.jpg', 'Persephone'),
('http://localhost:3001/villas/Phoebe/Phoebe1.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe2.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe3.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe4.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe5.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe6.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe7.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe8.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe9.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe10.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe11.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe12.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe13.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe14.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe15.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe16.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe17.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe18.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe19.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe20.jpg', 'Phoebe'),
('http://localhost:3001/villas/Phoebe/Phoebe21.jpg', 'Phoebe'),
('http://localhost:3001/villas/Thalassa/Thalassa1.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa2.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa3.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa4.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa5.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa6.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa7.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa8.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa9.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa10.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa11.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa12.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa13.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa14.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa15.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa16.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa17.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa18.jpg', 'Thalassa'),
('http://localhost:3001/villas/Thalassa/Thalassa19.jpg', 'Thalassa');