SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `LuxuryHolidaysGreece` ;
USE `LuxuryHolidaysGreece` ;

CREATE TABLE IF NOT EXISTS `LuxuryHolidaysGreece`.`blog` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `tags` VARCHAR(100),
  `cover` VARCHAR(45),
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `text1` VARCHAR(1000) NOT NULL,
  `image1` VARCHAR(45),
  `text2` VARCHAR(1000),
  `image2` VARCHAR(45),
  `text3` VARCHAR(1000),
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from blog;
